### ISSUE TITLE
Creación de una sección de Web Frameworks

### ISSUE THREAD

**Issue by carlosgruiz-dev** [pyve/awesome-pyve#14]
Se me ocurre que podemos crear una sección completa de Web Frameworks donde tengamos subsecciones con las herramientas particulares para cada uno. En caso que les haga sentido, como traduciríamos el término _Web Framework_.

Adicionalmente a ese caso ¿qué se haría con secciones como RESTful? ¿se dejan o se colocan como parte de las subcategorías?.

**Comment by hernanramirez** [comment]
Es buena idea. 

Es cuestión de organizar django REST es un framework. 

Creo que lo mas conveniente es usar “Marco de trabajo “ tal cual lo uso en tesis de maestria.  Para estos términos tan estandarizado seria genial hacer un párrafo introductorio.

**Comment by satanas** [comment]
Como comentaba en otro archivo, a mi todavía me suena raro `marco de trabajo`, yo diría dejar al anglicismo y linkear al glosario para que la gente que no lo entiende pueda aprender, sobretodo porque es un término común incluso en tutoriales y cosas en español. Sin embargo, si les parece mejor traducirlo, plomo.

**Comment by satanas** [comment]
¡Ah! Y la idea de la sección nueva me parece genial, ahí podemos meter flask, django, bottle et al.

**Comment by hernanramirez** [comment]
@satanas usar el anglicismo con una breve explicación de antesala.  

Creo que es muy buena idea..  Asi se van adaptando al english

**Comment by carlosgruiz-dev** [comment]
igual en el documento `GLOSARIO.md` podemos colocar nombres y anglicismos.. ejemplo: 
- Librería: ver biblioteca de programación [_link_]

**Comment by hernanramirez** [comment]
Sip..

Voy hacer el cambio a ver que tal queda

**Comment by hernanramirez** [comment]
Creo que esto ya lo podemos cerrar

**Comment by carlosgruiz-dev** [comment]
:+1:
