### ISSUE TITLE
epale e iPython

### ISSUE THREAD

**Issue by hernanramirez** [pyve/awesome-pyve#16]
Donde lo colocamos..

Considero que es algo muy importante que incluso debería encabezar la lista.

Actualmente lo estamos utilizando mucho para el análisis de datos en el [CIDA](http://www.cida.gob.ve)

**Comment by map0logo** [comment]
Yo estaba por ponerlo!!

Si puede poner en una sección de "herramientas" junto con los depuradores.
test unitarios, profilers, etc.

F. Palm

El 9 de agosto de 2015, 12:22 p. m., J. Hernán Ramírez R<
notifications@github.com> escribió:

> Donde lo colocamos..
> 
> Considero que es algo muy importante que incluso debería encabezar la
> lista.
> 
> Actualmente lo estamos utilizando mucho para el análisis de datos en el
> CIDA http://www.cida.gob.ve
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyve/awesome-pyve/issues/16.

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by hernanramirez** [comment]
Plomo con eso @map0logo

**Comment by hernanramirez** [comment]
Listo se complementa Utilidades de desarrollo y depuración
