### ISSUE TITLE
Sección para el frontend

### ISSUE THREAD

**Issue by satanas** [pyve/awesome-pyve#17]
¿Les parece si agregamos una sección para el frontend? Generalmente usamos cosas como bootstrap, foundation y así por el estilo para las aplicaciones web. Pregunto porque no es Python pero lo usamos con Python.

¿Qué opinan ustedes?

**Comment by hernanramirez** [comment]
Creo que si..

Solo recomendaria colocar a esa sección un nombre y un resumen a la medida para que no quede lugar a dudas del por qué está allí no siendo python.

@satanas: tu dices _"así por el estilo para las aplicaciones web"_ pero en Qt, pyQt, et at, pueden utilizarse cosas no python con python muy útiles quizás esta sección requiera ser más general y no solo web.

**Comment by carlosgruiz-dev** [comment]
@satanas @hernanramirez estoy totalmente de acuerdo que agreguemos contenidos de _no solo Python_, porque hay temas como los editores, cursos de inglés, frontend, integraciones, o simplemente recursos como repositorios (github, gitlab, bitbucket) que valdría la pena nombrar.

La idea es que alguién que llegue pueda tener recursos para armar su caja de herramientas. ¿Qué opinan?

**Comment by hernanramirez** [comment]
Sacaría curso de inglés.  Lo importante es que tenga relación pyrhon no importa si esta relación sea remota.

**Comment by satanas** [comment]
De acuerdo, incluso con los cursos de inglés. Me parece que una pequeña sección, bien discreta, que diga algo tipo "Recursos para aprender inglés" sería de mucha ayuda para jóvenes programadores que no saben de inglés. Obviamente, no es que vamos a desvirtuar la lista poniendo un montón de cosas que no tienen relación con la programación pero en éste caso lo de los cursos me parece que aplica (de manera indirecta).

**Comment by carlosgruiz-dev** [comment]
:grey_question:  déjenme saber si prefieren abrir un _Issue_ para depurar el criterio o prefieren irlo armando sobre la marcha.

**Comment by satanas** [comment]
Abre un issue, ahí podemos comentar y queda en el historial ;)

**Comment by carlosgruiz-dev** [comment]
listo en el #24
