### ISSUE TITLE
Crear sección de "Servicios para control de versiones"

### ISSUE THREAD

**Issue by satanas** [pyve/awesome-pyve#20]
Poner al menos github, gitlab y bitbucket

**Comment by hernanramirez** [comment]
Sip..  Eso es esencial para la gestión de versiones.

**Comment by carlosgruiz-dev** [comment]
:+1: vale en la misma sección tal vez convenga colocar recursos para aprender _git_. Salgo de un par de cosas y lo agrego.

**Comment by carlosgruiz-dev** [comment]
sorry.. lo coloco en otro apartado, porque vi que estos son servicios.. :no_mouth:
