### ISSUE TITLE
Crear sección para herramientas de gestión de proyectos

### ISSUE THREAD

**Issue by satanas** [pyve/awesome-pyve#21]
Pivotal tracker, trello, jira, etc

**Comment by hernanramirez** [comment]
Taiga. Io

Quizás en gestión de proyectos asociar git+server y quizas slack 

Herramientas integrales para la gestión de proyectos 

Creo que sería una sección fenomenal..

**Comment by carlosgruiz-dev** [comment]
Estoy trabajando sobre esta sección. Pregunta, ¿conocen alguno de los nombres que están en esta lista de alternativas? [Algunas alternativas a Pivotal Tracker](http://www.quora.com/What-are-some-alternatives-to-Pivotal-Tracker)

**Comment by hernanramirez** [comment]
Trello,  taiga.io, openone

Taiga es hecho con Python y es open source

**Comment by carlosgruiz-dev** [comment]
openone no lo tenia en lista :+1:

**Comment by carlosgruiz-dev** [comment]
no conseguí url para openone, el primer lote va en el #29 :steam_locomotive:

**Comment by jackboot7** [comment]
De esas alternativas, trabajo a diario con Trello. Hace muchos años trabajé con Assembla, en esa época estaba basado en SVN y se parecía más a SourceForge que a una herramienta de gestión de proyectos.

**Comment by hernanramirez** [comment]
Creo que este issue se puede cerrar.. ya la sección esta creada

**Comment by satanas** [comment]
Así es
