### ISSUE TITLE
Definición de criterios para incluír contenidos no exclusivos de Python.

### ISSUE THREAD

**Issue by carlosgruiz-dev** [pyve/awesome-pyve#24]
Se comentó en el Issue #17 la conveniencia de incluir recursos que aunque no estén directamente relacionadas con Python, permitan a una persona armar su juego de herramientas. Entre ellas se nombraron, editores de texto, herramientas frontend, herramientas de CI, entre otras. Este Issue es para definir los criterios para aceptar o no alguna herramienta o sección de este tipo.

**Comment by hernanramirez** [comment]
Excelente..

**Comment by hernanramirez** [comment]
Por comodidad he venido utilizando subleme text como editor Python django y otras hierbas 

Lo agregamos en la seccion de desarrollo?

**Comment by satanas** [comment]
Yo creo que esa sección en particular se merece su apartado "Editores de texto & IDEs" o algo así. ¿Qué dicen ustedes?

**Comment by carlosgruiz-dev** [comment]
concuerdo que usemos una sección llamada _Editores de Texto & IDEs_ y luego dentro se abra subsecciones para cada editor y sus plugins. Ej

---

### Editores de Texto & IDEs

#### SublimeText
- ...
- plugin: emmet
- plugin: python-*

#### VIM
- vim ...
- vundle
- pathogen
- airline

#### Emacs
- NPI :smile: 

---

Otras secciones que se hemos comentado son _Herramientas Front-end_ y las _Herramientas de Integración Continua_.

Sin embargo hay temas como cursos de idiomas o tal vez recursos tipo sysadmin que no se si les parece crear una sección llamada _Recursos Varios_ o _Otros Recursos Útiles_.

**Comment by hernanramirez** [comment]
De acuerdo con Editores de Texto & IDEs e integración continua

**Comment by hernanramirez** [comment]
Yo podría agregar contenido sysadmin.. tengo varios. Creo que es muy importante..

**Comment by satanas** [comment]
De acuerdo :+1:

**Comment by jgomo3** [comment]
Propongo como criterios Disjuntos (OR):
- El _awesome_ debe entender Python.
- El _awesome_ debe ser necesario para Python.
- El _awesome_ se puede usar con Python.

Vi cosas como Trello y Bootstrap. No entiendo por qué están aquí.

Un editor de texto es necesario para programar. Cumple con el segundo. También algunos cumplen con el primero, porque hacen resaltado de sintaxis y algunos autocompletan y se tienen un intérprete incluido.

Otras herramientas que utilicen Python, como Blender o QGIS y ARCGIS, tienen sentido estar incluidos. Proveen una API Python y una consola Python.

**Comment by satanas** [comment]
Trello lo usas con proyectos (de Python) y Bootstrap lo usas para web applications (en Python). Creo que ese fue el criterio que seguimos para agregar esos items

**Comment by hernanramirez** [comment]
@jgomo3 tal como dice @satanas ese fue el criterio. Utilidades para gestión de proyectos y diseño web con Python.

También habían otros criterios de formato que no escribimos. Una era colocar al final de la descripción en cursivas si estaba en inglés o español y si tenia un termino referenciarlo con link al glosario. Ya hay unos ejemplos que hicimos.

Será que hacemos un issues para hacer un documento de como colaborar + los criterios?

**Comment by satanas** [comment]
El PR https://github.com/pyve/awesome-pyve/pull/32 ya tiene el documento donde se pueden poner las instrucciones/criterios para colaborar. Puse lo básico que hemos comentado aquí, siéntanse libres de agregar cualquier otra cosa que haga falta
