### ISSUE TITLE
Zato: ESB y Servidor de Aplicaciones en Python.

### ISSUE THREAD

**Issue by jackboot7** [pyve/awesome-pyve#25]
Dónde colocarían algo como [Zato](https://zato.io/)? Se me ocurre `Recursos para el desarrollo de Backends`.

No tiene la popular que merece.

**Comment by map0logo** [comment]
Si en backends, si crece mucho se pondrán subcategorías...

**Comment by jackboot7** [comment]
Fino @map0logo.
