### ISSUE TITLE
Recomendación para usuarios usar PR

### ISSUE THREAD

**Issue by hernanramirez** [pyve/awesome-pyve#28]
Creo que @map0logo hizo push directo al repo.

¿Seria recomendable que todos usemos actualizaciones vía fork?

**Comment by satanas** [comment]
Sí, la idea es que todas las contribuciones sean vía PR. El code review es una de las mejores prácticas, permite que varias personas validen el cambio y ayuda a mantener el orden y la calidad del código (en este caso del contenido)

**Comment by carlosgruiz-dev** [comment]
creo que vamos teniendo necesidad de fijar una archivo de directrices para este repo (tanto del contenido como de cómo realizar aportes), en el #7 hay una referencia de otros repos similares..

**Comment by jackboot7** [comment]
Varios acá tenemos permisos para hacer commit directamente, personalmente, tengo como práctica no hacer merge de un PR que yo mismo hice, sino esperar a que algún otro participante lo haga, por lo mismo del code review.

**Comment by carlosgruiz-dev** [comment]
si, de hecho somos 9 personas en el equipo _Owners_, concuerdo que cada PR debería ser revisado y aprobado por alguien más..

**Comment by map0logo** [comment]
Hola, ya entendí PR = Pull Request

¿Cuál es la política? ¿Es necesario en un proyecto de esta (pequeña)
magnitud complicarlo?

2015-08-12 9:01 GMT-04:30 J. Hernán Ramírez R notifications@github.com:

> Creo que @map0logo https://github.com/map0logo hizo push directo al
> repo.
> 
> ¿Seria recomendable que todos usemos actualizaciones vía fork?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyve/awesome-pyve/issues/28.

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by map0logo** [comment]
Bueno, ya veo que Uds. son del tipo burocrático. Seguro que han trabajado
con jefes encima.

No tengo rollo, puedo trabajar a través de Pull Request porque lo demanda
la mayoría, yo no lo considero necesario.

2015-08-12 9:26 GMT-04:30 Carlos Gustavo Ruiz notifications@github.com:

> si, de hecho somos 9 personas en el equipo _Owners_, concuerdo que cada
> PR debería ser revisado y aprobado por alguien más..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyve/awesome-pyve/issues/28#issuecomment-130314263.

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by satanas** [comment]
No es trabajar con jefes encima @map0logo y tampoco es que somos burocráticos, se llama buenas prácticas. La idea es que otras personas revisen lo que haces para detectar posibles errores antes de mergear. Aunque el proyecto es pequeño somos muchos colaborando y esa es una buena manera de mantener el orden en la pea.

**Comment by map0logo** [comment]
Yo me remito a los hechos, antes habían hecho sus PRs y tenía unos cuantos
errores ortográficos y de transcripción, yo con mis commits directos quite
unos cuantos errores. DC 1 PR 0

El hecho de que se haga un Pull Request no garantiza nada, la buena
práctica es querer hacer las cosas bien.

Pero nada, me someto al sentimiento de la mayoría, ya veo que acá son bien
socialistas :-D burocráticos y centralizados.

El 12 de agosto de 2015, 6:07 p. m., Wil Alvareznotifications@github.com
escribió:

> No es trabajar con jefes encima @map0logo https://github.com/map0logo y
> tampoco es que somos burocráticos, se llama buenas prácticas. La idea es
> que otras personas revisen lo que haces para detectar posibles errores
> antes de mergear. Aunque el proyecto es pequeño somos muchos colaborando y
> esa es una buena manera de mantener el orden en la pea.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyve/awesome-pyve/issues/28#issuecomment-130468274.

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by satanas** [comment]
Si hubieses comentado en esos PR, los errores se corrigen antes del merge. Insisto, buenas prácticas ;)

**Comment by jackboot7** [comment]
En teoría el repositorio está abierto a que cualquiera de los +200 participantes del grupo pueda contribuir, usar PR nos pone a todos en igualdad de condiciones en mi opinión.  

Independientemente de los argumentos en contra o a favor de usar PR, se acordó el uso de estos para este repositorio, así que voy a cerrar este hilo.
