### ISSUE TITLE
Guidelines for awesomeness

### ISSUE THREAD

**Issue by carlosgruiz-dev** [pyve/awesome-pyve#7]
I found this doc "[The awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md)" so, maybe it's time to write our guidelines.

**Comment by jackboot7** [comment]
Esto es clave _`it's a curation, not a collection`_, en nuestro caso estamos intentando hacer ambas: por un lado recopilar los links que se han enviado a la lista, por otro, "curar" contenido awesome.

La verdad es que se debería hacer el trabajo en dos pasadas, recopilar links pero ir depurando la lista.
